apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-ingress
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argocd-ingress
    repoURL: https://github.com/ReinierNel/devops-demo.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
