apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game
  namespace: argo-cd
spec:
  destination:
    namespace: game
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/game/base
    repoURL: https://github.com/ReinierNel/devops-demo.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true